### ISSUE TITLE
White screen of death

### ISSUE THREAD

**Issue by nimoatwoodway** [danb35/freenas-iocage-nextcloud#62]
First of all thanks for this great script!

After some time using I get a white screen of death with the installation. Now the second time on a different server. It seems that's there a problem with the db connection.

Did anyone else has the same problem?

Here is the error log entry:

[Wed Apr 10 08:19:31.315439 2019] [proxy_fcgi:error] [pid 4287:tid 34469042432][client 10.60.9.241:12282] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'nextcloud'@'localhost' (using password: YES) in /usr/local/www/apache24/data/nextcloud/lib/private/DB/Connection.php:64\nStack trace:\n#0 /usr/local/www/apache24/data/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /usr/local/www/apache24/data/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /usr/local/www/apache24/data/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /usr/local/www/apache24/data/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /usr/local/www/apache24/data/nextcloud/lib/private/DB/Connection.php(151): Doctrine\\DBAL\\Connection->se...\nPHP message: PHP Fatal error: Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'nextcloud'@'localhost' (using password: YES) in /usr/local/www/apache24/data/nextcloud/lib/private/DB/Connection.php:64\nStack trace:\n#0 /usr/local/www/apache24/data/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /usr/local/www/apache24/data/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /usr/local/www/apache24/data/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /usr/local/www/apache24/data/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /usr/local/www/apache24/data/nextcloud/lib/private/DB/Connection.php(151): Doctrine\\DBAL\\Connection->se...\n'

These are my DB Dataset Settings
![image](https://user-images.githubusercontent.com/4716780/55856153-c5d0cd00-5b69-11e9-9684-b58ea1501601.png)

Or am I the first one?
I don't use SSL from the script since I have a reverse proxy running.
Thankful for any help!

EDIT: Just noticed that the folder /root/ is empty. After installation there was file containing the db login credentials... maybe something to do with than? Maybe theres a sort of autoclean the /root folder? But could not find any info on that.

**Comment by danb35** [comment]
The /root/ directory in your FreeNAS system should have the passwords file, and there's no autoclean process going on.  What version of FreeNAS are you using?  My guess is that you've been bitten by the issue that causes loss of mountpoints to the jail--check the README page under the "Status" heading for information and how to resolve it.

**Comment by nimoatwoodway** [comment]
Ohh yes, I've been bitten! I'm using version 11.2-U2.1

Unfortunately after remounting theres another problem because I get an internal server error.
In /var/log/nextcloud.log I get this error:

{"reqId":"duGJHYgoFAkzsp8HlDUt","level":3,"time":"2019-04-10T13:13:53+02:00","remoteAddr":"10.60.9.241","user":"--","app":"PHP","method":"GET","url":"\/","message":"fopen(\/mnt\/files\/dat
a_dir_writability_test_5cadcff185fed.tmp): failed to open stream: Permission denied at \/usr\/local\/www\/apache24\/data\/nextcloud\/lib\/private\/legacy\/util.php#795","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit\/605.1.15 (KHTML, like Gecko) Version\/12.1 Safari\/605.1.15","version":"15.0.5.3"}
{"reqId":"duGJHYgoFAkzsp8HlDUt","level":3,"time":"2019-04-10T13:13:53+02:00","remoteAddr":"10.60.9.241","user":"--","app":"index","method":"GET","url":"\/","message":{"Exception":"OCP\\Files\\NotFoundException","Message":"","Code":0,"Trace":[{"file":"\/usr\/local\/www\/apache24\/data\/nextcloud\/lib\/private\/Files\/Node\/Node.php","line":216,"function":"getFileInfo","class":"OC\\Files\\Node\\Node","type":"->","args":[]},{"file":"\/usr\/local\/www\/apache24\/data\/nextcloud\/lib\/private\/Files\/Node\/Node.php","line":117,"function":"getPermissions","class":"OC\\Files\\Node\\Node","type":"->","args":[]},{"file":"\/usr\/local\/www\/apache24\/data\/nextcloud\/lib\/private\/Files\/Node\/Folder.php","line":156,"function":"checkPermissions","class":"OC\\Files\\Node\\Node","type":"->","args":[4]},{"file":"\/usr\/local\/www\/apache24\/data\/nextcloud\/lib\/private\/Files\/AppData\/AppData.php","line":94,"function":"newFolder","class":"OC\\Files\\Node\\Folder","type":"->","args":["js"]},{"file":"\/usr\/local\/www\/apache24\/data\/nextcloud\/lib\/private\/Files\/AppData\/AppData.php","line":114,"function":"getAppDataFolder","class":"OC\\Files\\AppData\\AppData","type":"->","args":[]},{"file":"\/usr\/local\/www\/apache24\/data\/nextcloud\/lib\/private\/Template\/JSCombiner.php","line":97,"function":"newFolder","class":"OC\\Files\\AppData\\AppData","type":"->","args":["core"]},{"file":"\/usr\/local\/www\/apache24\/data\/nextcloud\/lib\/private\/Template\/JSResourceLocator.php","line":114,"function":"process","class":"OC\\Template\\JSCombiner","type":"->","args":["\/usr\/local\/www\/apache24\/data\/nextcloud","core\/js\/merged-template-prepend.json","core"]},{"file":"\/usr\/local\/www\/apache24\/data\/nextcloud\/lib\/private\/Template\/JSResourceLocator.php","line":70,"function":"cacheAndAppendCombineJsonIfExist","class":"OC\\Template\\JSResourceLocator","type":"->","args":["\/usr\/local\/www\/apache24\/data\/nextcloud","core\/js\/merged-template-prepend.json"]},{"file":"\/usr\/local\/www\/apache24\/data\/nextcloud\/lib\/private\/Template\/ResourceLocator.php","line":78,"function":"doFind","class":"OC\\Template\\JSResourceLocator","type":"->","args":["js\/merged-template-prepend"]},{"file":"\/usr\/local\/www\/apache24\/data\/nextcloud\/lib\/private\/TemplateLayout.php","line":328,"function":"find","class":"OC\\Template\\ResourceLocator","type":"->","args":[["vendor\/core","js\/merged-template-prepend","search\/js\/search","core\/l10n\/en","search\/l10n\/en","search\/js\/searchprovider","js\/jquery-ui-fixes","js\/files\/fileinfo","js\/files\/client","js\/contactsmenu","js\/contactsmenu_templates"]]},{"file":"\/usr\/local\/www\/apache24\/data\/nextcloud\/lib\/private\/TemplateLayout.php","line":160,"function":"findJavascriptFiles","class":"OC\\TemplateLayout","type":"::","args":[["vendor\/core","js\/merged-template-prepend","search\/js\/search","core\/l10n\/en","search\/l10n\/en","search\/js\/searchprovider","js\/jquery-ui-fixes","js\/files\/fileinfo","js\/files\/client","js\/contactsmenu","js\/contactsmenu_templates"]]},{"file":"\/usr\/local\/www\/apache24\/data\/nextcloud\/lib\/private\/legacy\/template.php","line":211,"function":"__construct","class":"OC\\TemplateLayout","type":"->","args":["guest",""]},{"file":"\/usr\/local\/www\/apache24\/data\/nextcloud\/lib\/private\/Template\/Base.php","line":132,"function":"fetchPage","class":"OC_Template","type":"->","args":[]},{"file":"\/usr\/local\/www\/apache24\/data\/nextcloud\/lib\/private\/legacy\/template.php","line":301,"function":"printPage","class":"OC\\Template\\Base","type":"->","args":[]},{"file":"\/usr\/local\/www\/apache24\/data\/nextcloud\/lib\/base.php","line":690,"function":"printGuestPage","class":"OC_Template","type":"::","args":["","error",{"errors":[{"error":"Your data directory is invalid","hint":"Ensure there is a file called \".ocdata\" in the root of the data directory."},{"error":"Your data directory is not writable","hint":"Permissions can usually be fixed by giving the webserver write access to the root directory. See https:\/\/docs.nextcloud.com\/server\/15\/go.php?to=admin-dir_permissions."}]}]},{"file":"\/usr\/local\/www\/apache24\/data\/nextcloud\/lib\/base.php","line":1068,"function":"init","class":"OC","type":"::","args":[]},{"file":"\/usr\/local\/www\/apache24\/data\/nextcloud\/index.php","line":40,"args":["\/usr\/local\/www\/apache24\/data\/nextcloud\/lib\/base.php"],"function":"require_once"}],"File":"\/usr\/local\/www\/apache24\/data\/nextcloud\/lib\/private\/Files\/Node\/Node.php","Line":97,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit\/605.1.15 (KHTML, like Gecko) Version\/12.1 Safari\/605.1.15","version":"15.0.5.3"}...

Probably some permission error...

But anyway.  This happens after 2 days of installation. If this happens once a week this setup is not usable for me. Do you know if this just happens once after init or maybe is fixed with 11.2-U3?

Many thanks for your info!

**Comment by nimoatwoodway** [comment]
...remaining error was caused of using /media/files as mount point and not /mnt/files. Maybe you could adjust this in your readme.

But when playing with setting mount points it happened again. All mount points where gone... Is this a problem of this setup or a problem in general with jails? This would be a really big bug wouldn't it? With a quick research I could not find a ticket for this do you know more about it?

**Comment by danb35** [comment]
I believe this problem with iocage is fixed in 11.1-U3.

**Comment by nimoatwoodway** [comment]
Great to hear! I will update and let you know if any problems persist! Many thanks for helping out!
